apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJaR0oxYzJobGJtdHZPbWRvY0Y5bk5HOVRSRzlZVEhGQmNGaEhaRTVxTWtSd1dUVnNXVGswWVZJMU9XVXpUalppVjFJPSJ9fX0=
type: kubernetes.io/dockerconfigjson
